# Generated by Django 4.1.2 on 2025-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_habitable', models.FloatField(verbose_name='Surface habitable (m²)')),
                ('hauteur_sous_plafond', models.FloatField(verbose_name='Hauteur sous plafond (m)')),
                ('volume_total', models.FloatField(verbose_name='Volume total (m³)')),
            ],
        ),
    ]
