# Generated by Django 4.1.2 on 2025-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dimensionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_habitable', models.FloatField(verbose_name='Surface habitable (m²)')),
                ('hauteur_sous_plafond', models.FloatField(verbose_name='Hauteur sous plafond (m)')),
                ('volume_total', models.FloatField(verbose_name='Volume total (m³)')),
                ('types_de_murs', models.CharField(max_length=255, verbose_name='Types de murs')),
                ('coefficient_transmission_thermique', models.FloatField(verbose_name='Coefficient de transmission thermique')),
                ('orientation', models.CharField(choices=[('Nord', 'Nord'), ('Sud', 'Sud'), ('Est', 'Est'), ('Ouest', 'Ouest')], max_length=10, verbose_name='Orientation')),
                ('epaisseur_des_isolants', models.FloatField(verbose_name='Épaisseur des isolants')),
                ('facteur_transmission_solaire', models.FloatField(verbose_name='Facteur de transmission solaire')),
                ('temperature_hiver', models.FloatField(verbose_name='Température intérieure souhaitée (°C) en hiver')),
                ('temperature_ete', models.FloatField(verbose_name='Température intérieure souhaitée (°C) en été')),
                ('consommation_chauffage_climatisation', models.FloatField(verbose_name='Consommation moyenne pour le chauffage et la climatisation (kWh)')),
                ('temperature_eau_chaude', models.FloatField(verbose_name='Température souhaitée de l’eau chaude (°C)')),
                ('consommation_eau_chaude', models.FloatField(verbose_name='Consommation moyenne d’eau chaude par occupant (L/jour)')),
                ('puissance_moyenne', models.FloatField(verbose_name='Puissance moyenne (W)')),
                ('duree_utilisation', models.FloatField(verbose_name='Durée quotidienne d’utilisation (h/jour)')),
                ('prix_energie', models.FloatField(verbose_name='Prix de l’énergie (€/kWh)')),
                ('budget_maximal', models.FloatField(verbose_name='Budget disponible (€)')),
                ('reduction_couts_initiaux', models.BooleanField(default=False, verbose_name='Réduction des coûts initiaux')),
                ('maximisation_independance_energetique', models.BooleanField(default=False, verbose_name='Maximisation de l’indépendance énergétique')),
                ('optimisation_efficacite_energetique', models.BooleanField(default=False, verbose_name='Optimisation de l’efficacité énergétique')),
                ('temperature_exterieure_moyenne', models.FloatField(verbose_name='Température extérieure moyenne annuelle (°C)')),
                ('duree_ensoleillement', models.FloatField(verbose_name='Durée moyenne d’ensoleillement par jour (h)')),
                ('irradiation_solaire_annuelle', models.FloatField(verbose_name='Irradiation solaire annuelle (kWh/m²)')),
            ],
        ),
        migrations.DeleteModel(
            name='Dimensionnement',
        ),
    ]
