# Generated by Django 4.1.2 on 2025-01-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_delete_dimensionnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coefficient_transmission_thermique',
        ),
        migrations.AddField(
            model_name='project',
            name='coefficient_transmission_murs',
            field=models.FloatField(default=0.5, verbose_name='Coefficient de transmission thermique des murs (W/m²·K)'),
        ),
        migrations.AddField(
            model_name='project',
            name='coefficient_transmission_plancher',
            field=models.FloatField(default=0.5, verbose_name='Coefficient de transmission thermique du plancher (W/m²·K)'),
        ),
        migrations.AddField(
            model_name='project',
            name='coefficient_transmission_toit',
            field=models.FloatField(default=0.5, verbose_name='Coefficient de transmission thermique du toit (W/m²·K)'),
        ),
        migrations.AddField(
            model_name='project',
            name='coefficient_transmission_vitrages',
            field=models.FloatField(default=0.5, verbose_name='Coefficient de transmission thermique des vitrages (W/m²·K)'),
        ),
        migrations.AddField(
            model_name='project',
            name='duree_eclairage',
            field=models.FloatField(default=8, verbose_name='Durée quotidienne d’éclairage (h/jour)'),
        ),
        migrations.AddField(
            model_name='project',
            name='prix_gaz',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix du gaz (€/kWh)'),
        ),
        migrations.AddField(
            model_name='project',
            name='puissance_ampoules',
            field=models.FloatField(default=10, verbose_name='Puissance moyenne des ampoules (W)'),
        ),
        migrations.AddField(
            model_name='project',
            name='surface_eclairage',
            field=models.FloatField(default=50, verbose_name='Surface totale à éclairer (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='surface_fenetres',
            field=models.FloatField(default=5, verbose_name='Surface totale des fenêtres (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='taux_renouvellement_air',
            field=models.FloatField(default=2, verbose_name='Taux de renouvellement d’air (renouvellements/h)'),
        ),
        migrations.AddField(
            model_name='project',
            name='type_ventilation',
            field=models.CharField(choices=[('naturelle', 'Naturelle'), ('mécanique simple flux', 'Mécanique simple flux'), ('double flux', 'Double flux')], default='naturelle', max_length=25, verbose_name='Type de ventilation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duree_utilisation',
            field=models.FloatField(verbose_name='Durée quotidienne d’utilisation des équipements (h/jour)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='epaisseur_des_isolants',
            field=models.FloatField(verbose_name='Épaisseur des isolants (mm)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='facteur_transmission_solaire',
            field=models.FloatField(verbose_name='Facteur de transmission solaire (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='orientation',
            field=models.CharField(choices=[('Nord', 'Nord'), ('Sud', 'Sud'), ('Est', 'Est'), ('Ouest', 'Ouest')], max_length=10, verbose_name='Orientation des fenêtres'),
        ),
        migrations.AlterField(
            model_name='project',
            name='puissance_moyenne',
            field=models.FloatField(verbose_name='Puissance moyenne des équipements (W)'),
        ),
    ]
