# Generated by Django 4.1.2 on 2025-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_project_coefficient_transmission_thermique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='types_de_murs',
            field=models.CharField(choices=[('béton', 'Béton'), ('brique', 'Brique'), ('bois', 'Bois')], max_length=50, verbose_name='Types de murs'),
        ),
    ]
