# Generated by Django 4.1.2 on 2025-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_project_types_de_murs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='irradiation_solaire_annuelle',
            field=models.FloatField(verbose_name='Irradiation solaire journalière (kWh/m²)'),
        ),
    ]
