# Generated by Django 4.1.2 on 2025-01-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='project',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='duree_moyenne_utilisation',
            field=models.FloatField(verbose_name="Durée moyenne d'utilisation (h/jour)"),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='nombre',
            field=models.PositiveIntegerField(verbose_name="Nombre d'équipements"),
        ),
    ]
